### ISSUE TITLE
在做PDF格式转换过程中出现问题

### ISSUE THREAD

**Issue by Err0rZero** [majinxin2003/PitGen#4]
D:\T00L\PitGen>python PitGen.py -f disk.pdf -t PDFTemplate.bt
Traceback (most recent call last):
  File "PitGen.py", line 237, in <module>
    GeneratePit(options.fileName, options.template)
  File "PitGen.py", line 24, in GeneratePit
    dom = pfp.parse(data_file=src, template_file=template)
  File "C:\Python27\lib\site-packages\pfp__init__.py", line 85, in parse
    keep_successful = keep_successful
  File "C:\Python27\lib\site-packages\pfp\interp.py", line 669, in parse
    self._ast = self._parse_string(template, predefines)
  File "C:\Python27\lib\site-packages\pfp\interp.py", line 809, in _parse_string
    keep_scopes=predefines
  File "C:\Python27\lib\site-packages\py010parser__init__.py", line 90, in parse_string
    keep_scopes     = keep_scopes
  File "C:\Python27\lib\site-packages\py010parser\c_parser.py", line 178, in parse
    debug=debuglevel)
  File "C:\Python27\lib\site-packages\py010parser\ply\yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "C:\Python27\lib\site-packages\py010parser\ply\yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "C:\Python27\lib\site-packages\py010parser\c_parser.py", line 1952, in p_error
    column=self.clex.find_tok_column(p)))
  File "C:\Python27\lib\site-packages\py010parser\plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
py010parser.plyparser.ParseError: <string>:4:6: before: int

目前为止并没有查找到原因。请指教。

**Comment by majinxin2003** [comment]
看起来貌似又是PFP模块出现问题，这个模块目前还不成熟，报错也情理之中。想解决的话还是得改它的代码。



At 2016-10-19 14:32:30, "Err0rZero" <notifications@github.com> wrote:


D:\T00L\PitGen>python PitGen.py -f disk.pdf -t PDFTemplate.bt
Traceback (most recent call last):
File "PitGen.py", line 237, in
GeneratePit(options.fileName, options.template)
File "PitGen.py", line 24, in GeneratePit
dom = pfp.parse(data_file=src, template_file=template)
File "C:\Python27\lib\site-packages\pfp__init__.py", line 85, in parse
keep_successful = keep_successful
File "C:\Python27\lib\site-packages\pfp\interp.py", line 669, in parse
self.ast = self.parse_string(template, predefines)
File "C:\Python27\lib\site-packages\pfp\interp.py", line 809, in _parse_string
keep_scopes=predefines
File "C:\Python27\lib\site-packages\py010parser__init.py", line 90, in parse_string
keep_scopes = keep_scopes
File "C:\Python27\lib\site-packages\py010parser\c_parser.py", line 178, in parse
debug=debuglevel)
File "C:\Python27\lib\site-packages\py010parser\ply\yacc.py", line 265, in parse
return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
File "C:\Python27\lib\site-packages\py010parser\ply\yacc.py", line 1047, in parseopt_notrack
tok = self.errorfunc(errtoken)
File "C:\Python27\lib\site-packages\py010parser\c_parser.py", line 1952, in p_error
column=self.clex.find_tok_column(p)))
File "C:\Python27\lib\site-packages\py010parser\plyparser.py", line 54, in _parse_error
raise ParseError("%s: %s" % (coord, msg))
py010parser.plyparser.ParseError: :4:6: before: int

目前为止并没有查找到原因。请指教。

**Comment by Err0rZero** [comment]
010转PIT的确非常累，你还有什么好的思路或者方法吗？

**Comment by majinxin2003** [comment]
已然是目前最自动化的方法了，要不然就是纯手写。






在 2016-10-20 13:57:26，"Err0rZero" <notifications@github.com> 写道：


010转PIT的确非常累，你还有什么好的思路或者方法吗？

**Comment by Err0rZero** [comment]
好吧，我还是去读一下PFP的源码吧，非常感谢。
